[package]
name = "websocket_service"
version = "0.1.0"
edition = "2021"

[alias]
test_connection = "test test_connection"

[workspace]
members = [
    "service",
    "websocket_derive",
]
default-members = ["service"]